days = {"monday","tuesday","wednesday","thursday", "friday","saturday","sunday","sunday","sunday","sunday"}
print(days)
print(type(days))
days=list(days)
days.remove("friday")
days.remove("sunday")
print(days)
days=set(days)
days.add("friday")
days.add("sunday")
print(days)
